      BLOCKDATA
      IMPLICIT NONE
      COMMON /GRAPHQWDATA/ CCLIENT
      CHARACTER*8 CCLIENT
      DATA CCLIENT /'SCANMF'/
      ENDBLOCKDATA
      PROGRAM MAIN
      IMPLICIT NONE
      CALL SUB1
      END
      SUBROUTINE SUB1
      END
